---
# Fail2Ban
- include_tasks: fail2ban.yml
  when: security_fail2ban_enabled | bool

# SSH
- include_tasks: ssh.yml

# Autoupdate
- include_tasks: autoupdate.yml
  when:
    - security_autoupdate_enabled | bool
